<template>
    <div class="btn-wrapper">
        <div class="card">
            <div class="card-header">
                default buttons
            </div>
            <div class="card-block">
                <customBtn
                    :style.sync="'primary'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :isWithIcon.sync="false"
                    :click.sync="clickBtn"
                    :message.sync="messages[0]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'secondary'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :isWithIcon.sync="false"
                    :click.sync="clickBtn"
                    :message.sync="messages[1]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'success'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :isWithIcon.sync="false"
                    :click.sync="clickBtn"
                    :message.sync="messages[2]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'warning'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :isWithIcon.sync="false"
                    :click.sync="clickBtn"
                    :message.sync="messages[3]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'danger'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :isWithIcon.sync="false"
                    :click.sync="clickBtn"
                    :message.sync="messages[4]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'link'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :isWithIcon.sync="false"
                    :click.sync="clickBtn"
                    :message.sync="messages[5]"
                >
                </customBtn>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                outlined button
            </div>
            <div class="card-block">
                <customBtn
                    :style.sync="'primary'"
                    :isOutline.sync="true"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :isWithIcon.sync="false"
                    :click.sync="clickBtn"
                    :message.sync="messages[0]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'secondary'"
                    :isOutline.sync="true"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :isWithIcon.sync="false"
                    :click.sync="clickBtn"
                    :message.sync="messages[1]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'success'"
                    :isOutline.sync="true"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :isWithIcon.sync="false"
                    :click.sync="clickBtn"
                    :message.sync="messages[2]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'warning'"
                    :isOutline.sync="true"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :isWithIcon.sync="false"
                    :click.sync="clickBtn"
                    :message.sync="messages[3]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'danger'"
                    :isOutline.sync="true"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :isWithIcon.sync="false"
                    :click.sync="clickBtn"
                    :message.sync="messages[4]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'link'"
                    :isOutline.sync="true"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :isWithIcon.sync="false"
                    :click.sync="clickBtn"
                    :message.sync="messages[5]"
                >
                </customBtn>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                with Icons
            </div>
            <div class="card-block">
                <customBtn
                    :style.sync="'primary'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :click.sync="clickBtn"
                    :isWithIcon.sync="true"
                    :iconName="'star'"
                    :message.sync="messages[0]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'secondary'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :click.sync="clickBtn"
                    :isWithIcon.sync="true"
                    :iconName.sync="'star'"
                    :message.sync="messages[1]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'success'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :click.sync="clickBtn"
                    :isWithIcon.sync="true"
                    :iconName.sync="'star'"
                    :message.sync="messages[2]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'warning'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :click.sync="clickBtn"
                    :isWithIcon.sync="true"
                    :iconName.sync="'star'"
                    :message.sync="messages[3]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'danger'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :click.sync="clickBtn"
                    :isWithIcon.sync="true"
                    :iconName.sync="'star'"
                    :message.sync="messages[4]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'link'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :click.sync="clickBtn"
                    :isWithIcon.sync="true"
                    :iconName.sync="'star'"
                    :message.sync="messages[5]"
                >
                </customBtn>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                size large
            </div>
            <div class="card-block">
                <customBtn
                    :style.sync="'primary'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :click.sync="clickBtn"
                    :size.sync="'large'"
                    :isWithIcon.sync="true"
                    :iconName="'star'"
                    :message.sync="messages[0]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'secondary'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :click.sync="clickBtn"
                    :size.sync="'large'"
                    :isWithIcon.sync="true"
                    :iconName.sync="'star'"
                    :message.sync="messages[1]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'success'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :click.sync="clickBtn"
                    :size.sync="'large'"
                    :isWithIcon.sync="true"
                    :iconName.sync="'star'"
                    :message.sync="messages[2]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'warning'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :click.sync="clickBtn"
                    :size.sync="'large'"
                    :isWithIcon.sync="true"
                    :iconName.sync="'star'"
                    :message.sync="messages[3]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'danger'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :click.sync="clickBtn"
                    :size.sync="'large'"
                    :isWithIcon.sync="true"
                    :iconName.sync="'star'"
                    :message.sync="messages[4]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'link'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :click.sync="clickBtn"
                    :size.sync="'large'"
                    :isWithIcon.sync="true"
                    :iconName.sync="'star'"
                    :message.sync="messages[5]"
                >
                </customBtn>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                size small
            </div>
            <div class="card-block">
                <customBtn
                    :style.sync="'primary'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :click.sync="clickBtn"
                    :size.sync="'small'"
                    :isWithIcon.sync="true"
                    :iconName="'star'"
                    :message.sync="messages[0]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'secondary'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :click.sync="clickBtn"
                    :size.sync="'small'"
                    :isWithIcon.sync="true"
                    :iconName.sync="'star'"
                    :message.sync="messages[1]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'success'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :click.sync="clickBtn"
                    :size.sync="'small'"
                    :isWithIcon.sync="true"
                    :iconName.sync="'star'"
                    :message.sync="messages[2]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'warning'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :click.sync="clickBtn"
                    :size.sync="'small'"
                    :isWithIcon.sync="true"
                    :iconName.sync="'star'"
                    :message.sync="messages[3]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'danger'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :click.sync="clickBtn"
                    :size.sync="'small'"
                    :isWithIcon.sync="true"
                    :iconName.sync="'star'"
                    :message.sync="messages[4]"
                >
                </customBtn>
                <customBtn
                    :style.sync="'link'"
                    :isOutline.sync="false"
                    :isBlock.sync="false"
                    :isDisabled.sync="false"
                    :click.sync="clickBtn"
                    :size.sync="'small'"
                    :isWithIcon.sync="true"
                    :iconName.sync="'star'"
                    :message.sync="messages[5]"
                >
                </customBtn>
            </div>
        </div>
    </div>
</template>
<script>
    import Button from '../../components/UiElements/Buttons.vue';

    export default {
        data() {
            return {
                messages: [
                    'Primary',
                    'Secondary',
                    'Success',
                    'Warning',
                    'Danger',
                    'Link'
                ]
            }
        },
        methods: {
            clickBtn: function (e) {
                console.log('in clickBtn');
                console.log(e);
            }
        },
        components: {
            customBtn: Button
        }
    }
</script>
<style>
</style>